stock | 188520..1885B0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 18854E
stock | 18A170..18A1E0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 18A18F
stock | 1BB900..1BBA70 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 1BBA48
stock | 2013D0..201430 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 20141B
stock | 202690..2026E0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 20269E
stock | 204BE0..204C90 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 204C7A
stock | 20E5D0..20E6E0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 20E645 20E6C4
stock | 212100..212140 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 21210F
stock | 21D470..21D4D0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 21D4AF
stock | 23ABA0..23AC00 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 23ABDA
stock | 23E630..23E6E0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 23E687
stock | 2EC860..2EC920 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 2EC8B4 2EC8C7
stock | 2ECE10..2ECE80 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 2ECE56 2ECE69
stock | 301A70..301BC0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 301B54 301B64
stock | 317810..317870 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 317845 31785A
stock | 33D700..33D780 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 33D73A
stock | 33DBA0..33DBE0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 33DBB9
stock | 35DAF0..35DB40 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 35DB2C
stock | 36EE50..36EEF0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 36EEC1
stock | 370D50..370E40 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 370DF0
stock | 3CF340..3CF440 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 3CF3DE
stock | 3F1280..3F12C0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 3F12A4
stock | 3FCBF0..3FCC10 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 3FCC05
stock | 40BFB0..40BFF0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 40BFD2
stock | 40FE90..40FEF0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 40FEB7
stock | 468750..468AA0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 46881C 4689DD 4689F5
stock | 469490..4697B0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 469516 469577 46958F 4695A7
stock | 46D680..46DA70 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 46D748 46D7A2 46D853 46D870 46D888
stock | 46DA70..46DCF0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 46DBAF 46DBC7
stock | 46DCF0..46E890 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 46DD99 46E1A6 46E235
stock | 470550..470AE0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 47064E 47066C 4706AB 4706C0 4706D8
stock | 471660..471C00 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 47175C 47177B 4717C1 4717D6 4717EE
stock | 471C00..472140 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 471C9D 471CBC 471D02 471D17 471D2F
stock | 472330..472CC0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 472803 47280A 47283D
stock | 478EF0..4797A0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 478FA0 479106 479127 4792A3 4792C7 4794B5 4794BC 4794D9 4794ED
stock | 47BAE0..47C9D0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 47BB73 47BD13 47BD34 47C03A 47C05F 47C074
stock | 47EC10..47F5F0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 47F0E3 47F0EA 47F11D
stock | 498E30..498E70 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 498E49
stock | 4A1DA0..4A1EB0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 4A1E30 4A1E53 4A1E69 4A1E8E
stock | 4AC140..4AC1A0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 4AC187
stock | 4FECB0..4FECF0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 4FECD7
stock | 510220..510290 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 510238 51024C 510263 51027A
stock | 5A2C60..5A2CA0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 5A2C87
stock | 5A3690..5A36F0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 5A36DE
stock | 5AA9C0..5AAA10 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 5AA9F6
stock | 5D4C50..5D4CC0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 5D4CAD
stock | 5DE130..5DE1A0 has no direct external entry, aligned or unaligned actual code pointer, switch/LEA reference, export reference or physical fallthrough. Generator rechecks this complete range on the audited image; unwind frame descriptions cannot invoke it. | 5DE18D
