stock | 13A670: record fields +3 and +6 are clamped selection indices after a -2 record-status marker. The branch rebuilds the record and clears that marker; neither field counts elapsed updates. | 13A703 13A715
stock | cPad::Lever_gacya_set: +9C is zeroed at function entry, then increased by 2/2/4 according to three angular sectors. These are contributions to the current input result returned to the caller. | 184343 184360 18437D
stock | 1987C0: allocation splits a free block by the requested element count. +18 advances by requested_count times 16 and +20 subtracts that count before assigning the allocated block. | 198897 19889B
stock | 198510: adjacent free blocks are coalesced when end-address equals next start-address. The word size adds the adjacent block's element count; it is heap bookkeeping. | 19854F
stock | 1B0AD0: +12CC issues a serial ID for each newly created load request, skipping ID zero on wrap. The resulting value is stored in the request before allocation and returned to the caller. | 1B0B99 1B0BA2
stock | 17E000: zero-initialized stack histograms count cells in a bounded 224-by-256 grid scan. A second histogram counts marked cells and both are consumed to compute coverage proportions during the same invocation. | 17E080 17E088
stock | 17F0B0: inserting one supplied record into a 30-element ring updates its read/write indices modulo 30 and its occupied-record count. The stored parameters and linked entries are data records, not a phase advanced independently of insertion. | 17F103 17F10B 17F153
stock | cPad::AdjusatCameraMove: both output shorts are initialized to zero or copied from the current stick axes before adding current trigger-axis differences clamped to 128. They compose this input sample and do not retain the previous update's values. | 182832 18283B 182854 182868
stock | cPad::AdjustCamera: +80/+84 are recomputed from current stick axes and dead zones earlier in every invocation. These later operations invert those current samples or subtract current mouse delta samples; none accumulates the preceding frame's camera orientation. | 182AA9 182AD0 182ADC 182B20 182B52 182BB5 182BD1
stock | 1CC780/1CC870/1CC960: each parser scans to its B8/BD/BB control tag, advances the text pointer by decoded token length times two, and returns the sum of token widths. These cursor and width results are produced within a single parse operation. | 1CC82C 1CC860 1CC91C 1CC950 1CCA0C 1CCA40
