# wp00 state handler (37F1E0)
once | wp00 state 37F1E0: state 0 performs one full-2pi target turn and immediately advances +E36, so the initial B4 write is a snap rather than a repeated rate | 37F300
once | wp00 state 37F1E0: the first successful collision latches +1100 and raises the accepted hit actor's +11B4 by 40 only on that event | 37F3E1
fixed | wp00 state 37F1E0: +B0's repeated 30-degree rising spin is scaled at lin 37F494, and +E3C's countdown is already stock-gated by memory_timers.h | 37F4A1 37F4B8

# wp05 state handler (385190)
once | wp05 state 385190: +E36 increments only on state-0 setup after selecting and starting the motion | 385246
follows | wp05 state 385190: after motion advance refreshes root motion, B4 gains the full freshly generated +EF4 root-yaw offset | 38533B

# wp1b grounded-flight helper (38E720)
fixed | wp1b helper 38E720: grounded slope changes persistent per-current-rate +E20/+E28 velocity by s^2 through the paired dst/pre rows | 38E7B2 38E7BA
stock | wp1b helper 38E720: position.x/z directly gains +E20/+E28, which already stores displacement for the current-rate tick | 38E7D6 38E7EE
fixed | wp1b helper 38E720: persistent +E20/+E28 damping uses decay_factors.h's 0.97^s conversion | 38E81B 38E82A

# wp1c grounded-flight helper (38F240)
fixed | wp1c helper 38F240: grounded half-slope changes persistent per-current-rate +E20/+E28 velocity by s^2 through the paired dst/pre rows | 38F2CA 38F2EA
stock | wp1c helper 38F240: position.x/z directly gains +E20/+E28, which already stores displacement for the current-rate tick | 38F306 38F31E
fixed | wp1c helper 38F240: persistent +E20/+E28 damping uses decay_factors.h's 0.94^s conversion | 38F34B 38F35A

# wp47 common state handler (39A840)
fixed | wp47 state 39A840: its normal path's two +10F6 decrements both commit on stock ticks; the special global path retains its immediate zero assignment | 39A89F 39A8C5

# pl05 state handler (3A7280)
fixed | pl05 state 3A7280: FixTurnRate converts the repeated 0.6 approach factor at the 2DA510 helper entry | 3A7395
stock | pl05 state 3A7280: +EC8 is freshly generated by motion advance, and multiplying that tick's root-motion component by 0.5 is a spatial shape rather than persistent damping | 3A73CB

# pl00 collision-event helper (3A8CD0)
once | pl00 event helper 3A8CD0: an accepted collision changes state, copies its hit point, and adjusts E14 by plus or minus 25 once for that event | 3A8DC2 3A8DEC

# pl00 state handler (3BC300)
stock | pl00 state 3BC300: +B8 and +E48 damping use port mode tables 7A8240 and 7A8218, already rewritten for the current rate by mode_constants.h | 3BC34B 3BC42F
fixed | pl00 state 3BC300, state 3: +E3C is stock-gated by lea_timers.h and its old-value zero transition is held between stock ticks; +E3E is stock-gated by memory_timers.h | 3BC4BD 3BC4D0

# pl00 state handler (3BD890)
stock | pl00 state 3BD890: +B8 damping uses port mode table 7A8240, already rewritten for the current rate by mode_constants.h | 3BD8C4
once | pl00 state 3BD890: state 0 performs one pi-limited target turn and immediately advances +E36 to 2 | 3BD9F6
stock | pl00 state 3BD890: +E54's repeated acceleration already includes the port time-scale global B6AC38 | 3BDA28
fixed | pl00 state 3BD890: +E48 uses decay_factors.h's 0.89^s conversion and then contributes its already-current-rate displacement directly to freshly generated root motion +EC8 | 3BDAF2 3BDB02

# pl00 state handler (3C1010)
stock | pl00 state 3C1010: +B8 damping uses port mode table 7A8240, already rewritten for the current rate by mode_constants.h | 3C1041
fixed | pl00 state 3C1010: the repeated B4 target turn uses the s-scaled 10-degree limit at lin 3C10FD | 3C112D
