#!/usr/bin/env python3
"""Find the engine's frame-counter rate gates and emit the C table.

Alongside the per-object timers the engine throttles repeating work straight
off the global frame counter at main+0xB6AC20:

    test byte ptr [rip+frameCounter], 7
    jne  skip
    ...                                  ; every eighth frame: spawn the effect
  skip:

That is how footstep dust, trail sparks, ripples, aura pulses and similar
repeating effects are rated. The mask is a tick count like any other duration,
so at 60 fps every one of them fires twice as often as it should and at 120 it
would fire four times as often.

The engine itself shows the intended conversion. Two sites in pl01 do the same
throttle as `frameCounter % (fps / 2)` instead of a mask, which tracks the
frame rate correctly -- the same story as the per-mode decay table, where the
port worked the right answer out in one place and left every other instance
alone.

Widening the mask is the whole fix: 7 becomes 15 at 60 fps and 31 at 120, one
byte per site, no cave and nothing to relocate. Every site taken here is the
memory form, whose only effect is on the flags the following `jne` reads, and
every one of them is `jne` -- a plain guard, never an if/else pair that would
change meaning when the period changes. Four further sites load the counter
into a register first and go on to use that register for something else; they
are left alone.

    python tools/find_frame_gates.py
"""
import collections
import os
import re
import sys

try:
    import pefile
    import capstone
except ImportError:
    sys.exit("needs pefile and capstone: pip install pefile capstone")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gamedir import GAME  # noqa: E402

BASE_IMAGE = 0x180000000
FRAME_COUNTER = 0xB6AC20
MASKS = {1, 3, 7, 0xF, 0x1F, 0x3F}          # 2^k - 1, and room to double twice
TESTMEM = re.compile(r"^byte ptr \[rip [+-] 0x[0-9a-f]+\], (0x[0-9a-f]+|\d+)$")
RIP = re.compile(r"\[rip ([+-]) 0x([0-9a-f]+)\]")


def disassemble(path):
    pe = pefile.PE(path, fast_load=True)
    img = pe.get_memory_mapped_image()
    text = [s for s in pe.sections if s.Name.startswith(b".text")][0]
    start, end = text.VirtualAddress, text.VirtualAddress + text.Misc_VirtualSize
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
    code = bytes(img[start:end])
    insns, off = [], 0
    while off < len(code):
        found = False
        for i in md.disasm(code[off:off + 65536], BASE_IMAGE + start + off):
            insns.append((i.address - BASE_IMAGE, i.mnemonic, i.op_str, i.size))
            off = i.address - BASE_IMAGE - start + i.size
            found = True
        if not found:
            off += 1
    return img, insns


def rip_target(a, op, size):
    m = RIP.search(op)
    if not m:
        return None
    d = int(m.group(2), 16)
    return a + size + (d if m.group(1) == "+" else -d)


def main():
    img, insns = disassemble(os.path.join(GAME, "main.dll"))
    rows = []
    for i, (a, m, o, s) in enumerate(insns):
        if m != "test" or rip_target(a, o, s) != FRAME_COUNTER:
            continue
        g = TESTMEM.match(o)
        if not g:
            continue
        text = g.group(1)
        mask = int(text, 16) if text.startswith("0x") else int(text)
        if mask not in MASKS:
            continue
        if insns[i + 1][1] != "jne":       # a guard, never an if/else pair
            continue
        rows.append((a, s - 1, mask, bytes(img[a:a + s])))

    rows.sort()
    counts = collections.Counter(r[2] for r in rows)
    out = [
        "// Generated by tools/find_frame_gates.py -- do not edit by hand.",
        "// See the README section \"Durations at 60 fps\".",
        "//",
        "// Each entry is one `test byte ptr [rip+frameCounter], N; jne skip` that lets",
        "// a repeating effect run only every (N+1)th frame. N is a tick count like any",
        "// other duration, so it doubles at 60 fps and quadruples at 120. Only the one",
        "// immediate byte is rewritten.",
        "//",
        "// %d sites: %s." % (len(rows),
                              ", ".join("mask 0x%X x%d" % (k, v)
                                        for k, v in sorted(counts.items()))),
        "",
        "struct FrameGate {",
        "    uint32_t rva;     // the test instruction",
        "    uint8_t immOff;   // where its mask byte sits",
        "    uint8_t mask;     // the stock mask",
        "    uint8_t orig[7];  // exactly what must be there",
        "};",
        "",
        "static const FrameGate kFrameGates[] = {",
    ]
    for rva, immoff, mask, raw in rows:
        body = ", ".join("0x%02X" % b for b in raw)
        out.append("    {0x%06X, %d, 0x%02X, {%s}},  // every %d frames"
                   % (rva, immoff, mask, body, mask + 1))
    out.append("};")

    dest = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                         "..", "src", "frame_gates.h"))
    with open(dest, "w", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("%d sites written to src/frame_gates.h" % len(rows))
    print("masks: %s" % dict(counts))


if __name__ == "__main__":
    main()
