#!/usr/bin/env python3
"""Find the UI oscillators driven straight off the frame counter.

Menus, pickups and enemy markers pulse by feeding the global frame counter at
main+0xB6AC20 into a sine:

    mov  eax, dword ptr [rip+frameCounter]
    lea  ecx, [rax + rax*4]
    add  ecx, ecx                         ; ecx = frame * 10
    ...                                   ; ecx % 360
    cvtsi2ss xmm0, rax
    call sin

Ten degrees a frame is a 36-frame cycle, which is 1.2 s at 30 fps, 0.6 s at 60
and would be 0.3 s at 120. This is most of what is left of "the interface still
looks hurried": the option screens, the save screen, the treasure and vital
pickups, and the enemy marker all wobble at double speed.

objScroll is deliberately excluded. It bumps the global frame counter by one
around a nested update so that its second scroll layer runs a frame out of
phase with the first, and a counter derived once per frame cannot reproduce
that trick -- the two layers would come out identical, which would look worse
than the speed does.

The fix is the same displacement-only retarget the phase steps and decay
factors use: each of these reads is the plain 6- or 7-byte rip-relative form,
so only its 4-byte displacement is rewritten, to a private dword the patch
keeps at `frameCounter >> shift`. Nothing else that reads the counter -- the
rate gates, the `frame % (fps/2)` throttles, the "have I already run this
frame" comparisons -- is affected.

    python tools/find_frame_phases.py
"""
import collections
import os
import re
import sys

try:
    import pefile
    import capstone
except ImportError:
    sys.exit("needs pefile and capstone: pip install pefile capstone")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gamedir import GAME  # noqa: E402

BASE_IMAGE = 0x180000000
FRAME_COUNTER = 0xB6AC20
RIP = re.compile(r"\[rip ([+-]) 0x([0-9a-f]+)\]")
# the two magic-number divisions the oscillators use: x % 360 and x % 3600
MAGIC = (("0x6c16c16d", "0x168"), ("0x91a2b3c5", "0xe10"))
EXCLUDE = ("objScroll",)


def disassemble(path):
    pe = pefile.PE(path, fast_load=True)
    img = pe.get_memory_mapped_image()
    text = [s for s in pe.sections if s.Name.startswith(b".text")][0]
    start, end = text.VirtualAddress, text.VirtualAddress + text.Misc_VirtualSize
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
    code = bytes(img[start:end])
    insns, off = [], 0
    while off < len(code):
        found = False
        for i in md.disasm(code[off:off + 65536], BASE_IMAGE + start + off):
            insns.append((i.address - BASE_IMAGE, i.mnemonic, i.op_str, i.size))
            off = i.address - BASE_IMAGE - start + i.size
            found = True
        if not found:
            off += 1
    return img, insns


def rip_target(a, op, size):
    m = RIP.search(op)
    if not m:
        return None
    d = int(m.group(2), 16)
    return a + size + (d if m.group(1) == "+" else -d)


def class_map():
    import bisect
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "rtti_classes.txt")
    if not os.path.exists(path):
        return lambda rva: "?"
    anchors = []
    for ln in open(path):
        p = ln.split()
        if len(p) < 4:
            continue
        for m in p[4:]:
            try:
                anchors.append((int(m, 16), p[1]))
            except ValueError:
                pass
    anchors.sort()
    aa = [a for a, _ in anchors]

    def owner(rva):
        i = bisect.bisect_right(aa, rva) - 1
        if i < 0:
            return "?"
        a, n = anchors[i]
        return n.replace(".?AV", "").replace("@@", "") if rva - a < 0x8000 else "?"
    return owner


def main():
    img, insns = disassemble(os.path.join(GAME, "main.dll"))
    owner = class_map()
    rows = []
    for i, (a, m, o, s) in enumerate(insns):
        if m != "mov" or rip_target(a, o, s) != FRAME_COUNTER:
            continue
        dst = o.split(",")[0].strip()
        if "ptr" in dst or not dst.startswith(("e", "r")):
            continue          # a store, or not a plain register load
        if s not in (6, 7):
            continue
        window = " ".join("%s %s" % (insns[j][1], insns[j][2])
                          for j in range(i, min(i + 16, len(insns))))
        if not any(all(t in window for t in pair) for pair in MAGIC):
            continue
        cls = owner(a)
        if cls in EXCLUDE:
            continue
        rows.append((a, s, s - 4, cls, bytes(img[a:a + s])))

    rows.sort()
    out = [
        "// Generated by tools/find_frame_phases.py -- do not edit by hand.",
        "// See the README section \"Durations at 60 fps\".",
        "//",
        "// Each entry is one plain rip-relative read of the global frame counter whose",
        "// value is turned straight into an oscillator phase (frame * 10 degrees, or",
        "// frame degrees out of 3600). Only the 4-byte displacement is rewritten, to a",
        "// private dword the patch keeps at frameCounter >> shift, so no other reader",
        "// of the counter is affected.",
        "//",
        "// %d sites: %s." % (
            len(rows),
            ", ".join("%s x%d" % (c, n) for c, n in
                      collections.Counter(r[3] for r in rows).most_common())),
        "",
        "struct FramePhase {",
        "    uint32_t rva;      // the load",
        "    uint8_t len;       // 6, or 7 with a REX prefix",
        "    uint8_t dispOff;   // where its displacement sits (always len - 4)",
        "    uint8_t orig[7];   // exactly what must be there",
        "};",
        "",
        "static const FramePhase kFramePhases[] = {",
    ]
    for rva, ln, dispoff, cls, raw in rows:
        body = ", ".join("0x%02X" % b for b in raw)
        pad = ", ".join(["0x00"] * (7 - len(raw)))
        out.append("    {0x%06X, %d, %d, {%s%s}},  // %s"
                   % (rva, ln, dispoff, body, (", " + pad) if pad else "", cls))
    out.append("};")

    dest = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                         "..", "src", "frame_phases.h"))
    with open(dest, "w", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("%d sites written to src/frame_phases.h" % len(rows))
    print("classes: %s" % dict(collections.Counter(r[3] for r in rows)))


if __name__ == "__main__":
    main()
