// Generated by tools/gen_brush_watch.py -- do not edit.
// What the Rejuvenation watch reads (brush_watch_runtime.h). Each address is
// checked against the instructions that use it; the evidence is below.
#pragma once
#include <cstdint>

#define BRUSH_WATCH_MAIN_SHA1 "703d292ab2cb50cc9e237e44722dec51d956b79c"
static const uint32_t kBrushRva = 0x8909C0;            // the brush object
static const uint32_t kBrushStateOff = 0xC80;       // 0 idle .. 3 evaluate .. 6 close
static const uint32_t kBrushEngagedOff = 0xC84;     // the engaged target, -1 none
static const uint32_t kBrushCandidateOff = 0xCB8;   // the target on offer, -1 none
static const uint32_t kBrushRequestOff = 0xCC8;     // mask capture requested (one tick)
static const uint32_t kBrushSavedMaskRva = 0x7F5210;  // 256 x 224 bytes, x * 224 + y
static const uint32_t kBrushPointsRva = 0x803650;     // records of kBrushPointSize
static const uint32_t kBrushPointSize = 0xB0;      // +0 flag, +4 x, +8 y, +0xC size
static const uint32_t kBrushPointCountRva = 0x888C64; // records the evaluation inks
static const uint32_t kBrushStrokeCountRva = 0x888C58;
static const uint32_t kBrushRatioRva = 0x892898;      // inked / (masked * 0.4)
static const uint32_t kBrushBitsRva = 0x803234;       // non-zero: restored
static const uint32_t kBrushMapRva = 0xB6B240;        // a word; 0x312 has seven masks
static const double kBrushNeed = 0.4;
static const int kBrushCanvasW = 256, kBrushCanvasH = 224;

// Every instruction below is checked byte for byte before the watch starts.
struct BrushEvidence { uint32_t rva; uint8_t len; uint8_t bytes[15]; };
static const BrushEvidence kBrushEvidence[] = {
    {0x169000, 6, {0x8B, 0x81, 0xC8, 0x0C, 0x00, 0x00}},
    {0x16CAA0, 6, {0x8B, 0x86, 0x80, 0x0C, 0x00, 0x00}},
    {0x16CAA6, 2, {0xFF, 0xC8}},
    {0x16D71D, 7, {0x83, 0x3D, 0x34, 0xB5, 0x71, 0x00, 0x1F}},
    {0x17B9B2, 6, {0x89, 0x3D, 0x7C, 0x78, 0x68, 0x00}},
    {0x17B9B8, 6, {0x8B, 0x81, 0x84, 0x0C, 0x00, 0x00}},
    {0x17B9E9, 7, {0x83, 0xB9, 0xB8, 0x0C, 0x00, 0x00, 0x22}},
    {0x17BA15, 7, {0x48, 0x8D, 0x15, 0xF4, 0xB7, 0x66, 0x00}},
    {0x17BA1C, 7, {0x48, 0x8D, 0x0D, 0xED, 0x97, 0x67, 0x00}},
    {0x17BA2A, 7, {0x48, 0x8D, 0x0D, 0xDF, 0xB7, 0x66, 0x00}},
    {0x17BAC1, 10, {0xC7, 0x05, 0x69, 0x77, 0x68, 0x00, 0x01, 0x00, 0x00, 0x00}},
    {0x17BB02, 7, {0x48, 0x8D, 0x05, 0x07, 0x97, 0x67, 0x00}},
    {0x17BB96, 7, {0x48, 0x8D, 0x0D, 0x73, 0xB6, 0x66, 0x00}},
    {0x17BBBC, 6, {0x39, 0x3D, 0x72, 0x76, 0x68, 0x00}},
    {0x17DD12, 8, {0xF3, 0x0F, 0x11, 0x1D, 0x7E, 0x4B, 0x71, 0x00}},
    {0x17DD24, 7, {0x66, 0x39, 0x05, 0x15, 0xD5, 0x9E, 0x00}},
    {0x17DD33, 8, {0xF2, 0x0F, 0x59, 0x05, 0x15, 0x7D, 0x4F, 0x00}},
    {0x17DD55, 8, {0xF3, 0x0F, 0x11, 0x0D, 0x3B, 0x4B, 0x71, 0x00}},
    {0x17DD60, 10, {0xC7, 0x05, 0xC6, 0x54, 0x68, 0x00, 0x00, 0x00, 0x00, 0x00}},
    {0x17DD7B, 6, {0x89, 0x05, 0xAF, 0x54, 0x68, 0x00}},
    {0x17DD9F, 6, {0x09, 0x05, 0x8F, 0x54, 0x68, 0x00}},
    {0x17ECC4, 6, {0x8B, 0x05, 0x9A, 0x9F, 0x70, 0x00}},
    {0x17ECD7, 7, {0x4C, 0x8D, 0x15, 0x76, 0x49, 0x68, 0x00}},
    {0x17ED05, 5, {0x41, 0x80, 0x7A, 0xFC, 0x00}},
    {0x17ED10, 6, {0xF3, 0x45, 0x0F, 0x2C, 0x4A, 0x08}},
    {0x17ED16, 6, {0xF3, 0x41, 0x0F, 0x2C, 0x4A, 0x04}},
    {0x17ED27, 5, {0xF3, 0x45, 0x0F, 0x2C, 0x1A}},
    {0x17EDA2, 7, {0x49, 0x81, 0xC2, 0xB0, 0x00, 0x00, 0x00}},
    {0x3E5DEF, 7, {0x48, 0x8D, 0x0D, 0xCA, 0xAB, 0x4A, 0x00}},
    {0x3E5DF6, 5, {0xE8, 0x05, 0x32, 0xD8, 0xFF}},
    {0x4B5326, 7, {0x48, 0x8D, 0x0D, 0x93, 0xB6, 0x3D, 0x00}},
    {0x4B532D, 5, {0xE8, 0xDE, 0x6C, 0xCC, 0xFF}},
};

// Evidence:
//   brush object     main+8909C0  lea rcx before the call to the brush init main+17C010 at main+4B5326 (the init loads etc/cock/fude_000.dds)
//   state            +0xC80       switch index at main+16CAA0 in the update main+16C7E0 (mov eax; dec eax; cmp eax, 5; ja: states 1-6, 0 the default)
//   stroke count     main+888C58  cmp [rip], 0x1f; jge at main+16D71D
//   coverage check   main+17DC90  mulsd by the double 0.4 at main+675A50; test byte [mask], 1
//   ratio            main+892898  the one float the coverage check stores
//   result           main+803230  the dword it sets to the mask's index + 1 on success
//   success bits     main+803234  the dword it ORs 1 << index into
//   map id           main+B6B240  compared with 0x312 (the one map with seven masks)
//   evaluation       main+17B9A0  the only caller of the coverage check
//   engaged target   +0xC84       mov eax, [rcx+K]; ...; js (returns at once if < 0)
//   candidate        +0xCB8       cmp [rcx+K], 0x22 (one special target)
//   saved mask       main+7F5210  memcpy(saved, ink, 0xE000) in the evaluation
//   ink canvas       main+7E7210  the same copy's source; the coverage check reads it
//   rasterizer       main+17ECC0  the evaluation's callee that ORs 1 into the ink canvas
//   points           main+803650  records of 0xB0: flag byte, then x, y, size floats; a point inks a square of half-width (int)size >> 2 at ((int)x >> 1, (int)y >> 1)
//   point count      main+888C64  the number of records the rasterizer inks
//   capture request  +0xCC8       getter main+169000, called by the renderer at main+3E5DEF before the capture
//   capture          main+3E47F0  renders the target to RT 10, copies it to a texture of its own format, maps it, fills the saved mask
