// Generated by tools/find_mode_multipliers.py -- do not edit by hand.
// See the README section "120 fps and the mode byte".
//
// The integer half of the mode-byte family: `n * (mode == 1 ? 2 : 1)`,
// where n is a duration in ticks. The mode byte is 1 at 120 fps as well, so
// each of these doubles where it needs to quadruple and whatever it times
// runs at exactly twice the speed it should.
//
// The hard-coded 2 becomes a dword the patch holds at 2 in 60 fps mode and 4
// in 120 fps mode, so 60 fps is reproduced exactly.

// how the stub rebuilds each site
enum ModeMultShape {
    kMultImulEax = 0,   // copy; jne L; imul eax,[mult]; L: jmp resume
    kMultMovsxEdx = 1,  // copy movsx; jne L; mov eax,edx; imul; jmp resume; L: jmp alt
    kMultSeteR9 = 2,    // jne L; mov r9d,[mult]; jmp M; L: mov r9d,1; M: jmp resume
    kMultSeteEbx = 3,   // as above in ebx, then the displaced lea
    kMultCmp2Eax = 4,   // copy; cmp eax,2; jne L; mov eax,[mult]; L: jmp resume
};

struct ModeMult {
    uint32_t rva;        // where the detour goes
    uint32_t resume;     // where the stub rejoins
    uint32_t altResume;  // the second exit, for kMultMovsxEdx
    uint8_t len;         // bytes displaced
    uint8_t shape;
    uint8_t orig[10];    // exactly what must be there
    const char* what;
};

static const ModeMult kModeMults[] = {
    {0x1B8C36, 0x1B8C42, 0x000000, 8, 0, {0x0F, 0xBF, 0x84, 0x91, 0x84, 0x02, 0x00, 0x00, 0x00, 0x00}, "UI layout colour track length"},  // guard at 1B8C29
    {0x1B8C68, 0x1B8C71, 0x1B8C72, 6, 1, {0x0F, 0xBF, 0x14, 0x81, 0x75, 0x04, 0x00, 0x00, 0x00, 0x00}, "UI layout position track length"},  // guard at 1B8C5D
    {0x1B8C96, 0x1B8CA2, 0x000000, 8, 0, {0x0F, 0xBF, 0x84, 0x91, 0x20, 0x02, 0x00, 0x00, 0x00, 0x00}, "UI layout rotation track length"},  // guard at 1B8C89
    {0x1B8CCB, 0x1B8CD4, 0x1B8CD5, 6, 1, {0x0F, 0xBF, 0x14, 0x81, 0x75, 0x04, 0x00, 0x00, 0x00, 0x00}, "UI layout scale track length"},  // guard at 1B8CC0
    {0x1B4768, 0x1B476F, 0x000000, 7, 2, {0x41, 0x0F, 0x94, 0xC1, 0x41, 0xFF, 0xC1, 0x00, 0x00, 0x00}, "UI layout keyframe search compare"},  // guard at 1B475D
    {0x1B47D6, 0x1B47DF, 0x000000, 9, 3, {0x0F, 0x94, 0xC3, 0x4C, 0x8D, 0x14, 0x40, 0xFF, 0xC3, 0x00}, "UI layout keyframe interpolation span"},  // guard at 1B47CB
    {0x4BA141, 0x4BA148, 0x000000, 7, 4, {0x44, 0x89, 0xB6, 0xA8, 0x0E, 0x00, 0x00, 0x00, 0x00, 0x00}, "motion blend length (cKamikiFree +0xF50)"},  // guard at 4BA11D
};
