// Generated by tools/find_mode_constants.py -- do not edit by hand.
// See the README section "120 fps and the mode byte".
//
// The engine picks its frame-rate-dependent constants by testing the mode
// byte (main+0xB6AC45), which is 1 for the fast configuration whether that is
// 60 fps or 120. Every one of these therefore returns the 60 fps value at
// 120 fps, and everything damped or advanced through them runs at half the
// rate it should.
//
// 60 damping table entries and 6 selected constants.

// A pre-computed {k**0.5, k} pair indexed by (mode - 1). The mode-1 slot is
// rewritten to k**timeScale, which reproduces the shipped value at 60 fps.
struct ModeTable {
    uint32_t rva;     // the mode-1 slot
    float fast;       // what the engine ships there (k**0.5)
    float stock;      // the mode-2 slot, k itself
    uint8_t indexed;  // 1 if a mode-byte lookup reaches this entry directly
};

static const ModeTable kModeTables[] = {
    {0x7A8150, 0.994989991f, 0.99000001f, 0},
    {0x7A8158, 0.989950001f, 0.980000019f, 0},
    {0x7A8160, 0.984889984f, 0.970000029f, 0},
    {0x7A8168, 0.979799986f, 0.959999979f, 0},
    {0x7A8170, 0.974680007f, 0.949999988f, 0},
    {0x7A8178, 0.96954f, 0.939999998f, 1},   // read by a mode-byte lookup
    {0x7A8180, 0.964370012f, 0.930000007f, 0},
    {0x7A8188, 0.959169984f, 0.920000017f, 0},
    {0x7A8190, 0.953939974f, 0.910000026f, 0},
    {0x7A8198, 0.948679984f, 0.899999976f, 0},
    {0x7A81A0, 0.943400025f, 0.889999986f, 0},
    {0x7A81A8, 0.938080013f, 0.879999995f, 0},
    {0x7A81B0, 0.932739973f, 0.870000005f, 0},
    {0x7A81B8, 0.927359998f, 0.860000014f, 0},
    {0x7A81C0, 0.921949983f, 0.850000024f, 0},
    {0x7A81C8, 0.91652f, 0.839999974f, 0},
    {0x7A81D0, 0.911040008f, 0.829999983f, 0},
    {0x7A81D8, 0.905539989f, 0.819999993f, 0},
    {0x7A81E0, 0.899999976f, 0.810000002f, 0},
    {0x7A81E8, 0.894429982f, 0.800000012f, 1},   // read by a mode-byte lookup
    {0x7A81F0, 0.888819993f, 0.790000021f, 0},
    {0x7A81F8, 0.883180022f, 0.779999971f, 0},
    {0x7A8200, 0.877499998f, 0.769999981f, 0},
    {0x7A8208, 0.871779978f, 0.75999999f, 0},
    {0x7A8210, 0.866029978f, 0.75f, 0},
    {0x7A8218, 0.860230029f, 0.74000001f, 0},
    {0x7A8220, 0.854399979f, 0.730000019f, 0},
    {0x7A8228, 0.848529994f, 0.720000029f, 0},
    {0x7A8230, 0.842649996f, 0.709999979f, 0},
    {0x7A8238, 0.836669981f, 0.699999988f, 0},
    {0x7A8240, 0.774600029f, 0.600000024f, 1},   // read by a mode-byte lookup
    {0x7A8248, 0.707107008f, 0.5f, 0},
    {0x7A8250, 0.632456005f, 0.400000006f, 0},
    {0x7A8258, 0.547722995f, 0.300000012f, 0},
    {0x7A8260, 0.447214007f, 0.200000003f, 0},
    {0x7A8268, 0.387297988f, 0.150000006f, 0},
    {0x7A8270, 0.316228002f, 0.100000001f, 0},
    {0x7A8278, 0.300000012f, 0.0900000036f, 0},
    {0x7A8280, 0.282842994f, 0.0799999982f, 0},
    {0x7A8288, 0.264575005f, 0.0700000003f, 0},
    {0x7A8290, 0.244948998f, 0.0599999987f, 0},
    {0x7A8298, 0.223607004f, 0.0500000007f, 0},
    {0x7A82A0, 0.200000003f, 0.0399999991f, 0},
    {0x7A82A8, 0.173205003f, 0.0299999993f, 0},
    {0x7A82B0, 0.141421005f, 0.0199999996f, 0},
    {0x7A82C0, 1.04881001f, 1.10000002f, 1},   // read by a mode-byte lookup
    {0x7A82C8, 1.07237995f, 1.14999998f, 0},
    {0x7A82D0, 1.09545004f, 1.20000005f, 1},   // read by a mode-byte lookup
    {0x7A82D8, 1.14017999f, 1.29999995f, 1},   // read by a mode-byte lookup
    {0x7A82E0, 1.18322003f, 1.39999998f, 0},
    {0x7A82E8, 1.22474003f, 1.5f, 0},
    {0x7A82F0, 1.26490998f, 1.60000002f, 0},
    {0x7A82F8, 1.30384004f, 1.70000005f, 0},
    {0x7A8300, 1.34164f, 1.79999995f, 0},
    {0x7A8308, 1.37839997f, 1.89999998f, 0},
    {0x7A8310, 1.00498998f, 1.00999999f, 0},
    {0x7A8318, 1.00995004f, 1.01999998f, 0},
    {0x7A8320, 1.01489997f, 1.02999997f, 0},
    {0x7A8328, 1.01979995f, 1.03999996f, 0},
    {0x7A8330, 1.02470005f, 1.04999995f, 0},
};

// `movss xmm, dword ptr [rip+0.5]` on the 60 fps side of a mode-byte test.
// 0.5 is shared, so the instruction is retargeted rather than the constant
// rewritten.
struct ModeSelect {
    uint32_t rva;      // the movss
    uint8_t orig[8];   // exactly what must be there
};

static const ModeSelect kModeSelects[] = {
    {0x19E121, {0xF3, 0x0F, 0x10, 0x35, 0xDF, 0x3C, 0x4D, 0x00}},
    {0x19E4BA, {0xF3, 0x0F, 0x10, 0x3D, 0x46, 0x39, 0x4D, 0x00}},
    {0x1A4028, {0xF3, 0x0F, 0x10, 0x35, 0xD8, 0xDD, 0x4C, 0x00}},
    {0x20F279, {0xF3, 0x0F, 0x10, 0x15, 0x87, 0x2B, 0x46, 0x00}},
    {0x475BF9, {0xF3, 0x0F, 0x10, 0x15, 0x07, 0xC2, 0x1F, 0x00}},
    {0x4B9CA9, {0xF3, 0x0F, 0x10, 0x3D, 0x57, 0x81, 0x1B, 0x00}},
};
