// Tracer runtime -- stage 0.6 of the animation plan (OKAMI_TRACER builds only).
//
// Installs the stub pool generated by tools/gen_tracer.py: one neutral,
// instrumented stub per animation candidate. Every stub runs its window's
// original instructions unchanged and records, around the candidate's store,
// how often the field is written, whether the write changed it, and on which
// ticks (the game's frame counter) and in which mode (the mode byte).
// tools/verify_tracer.py proves by emulation that each stub leaves registers,
// flags and memory exactly as the original bytes do.
//
// The session: the tracer build always runs as Passthrough (the stock game --
// the records must describe stock behaviour, and the real mode byte then says
// which context each tick was in). The overlay shows the current route step;
// the tracer key ends it, writes okami_tracer\phaseNN_<step>.csv and starts
// the next. A partial file is rewritten every AutosaveSeconds, so a crash loses
// at most that much.
//
// Safety:
//   * every window's bytes are compared with the header before anything is
//     written; one mismatch and nothing is installed;
//   * all other threads are suspended while the jumps are written, and the
//     write is retried until no thread is stopped inside a window;
//   * each window's bytes after its 5-byte jump are int3, and a vectored handler
//     sends any thread that lands on one to the matching point in the stub --
//     so a branch target the generator missed is logged, not a crash;
//   * a window whose sites run more than ShedPerSecond times a second has its
//     original bytes put back; and if the tick rate stays under 27/s for 6 s
//     (stock never runs below 30), the busiest windows are shed until it
//     recovers -- so the tracer cannot slow the game down for long, and every
//     step's file records its tick rate and how long it was slow.
//
// Included once from dinput8_proxy.cpp, which provides logf, allocNear,
// gameHasFocus, parseVk, g_eng, g_cfg and g_baseDir.

#include <tlhelp32.h>

#include <cstddef>

#include "generated/tracer_sites.h"

struct TracerRec {
    uint64_t old;        // the field just before the store (written by the stub)
    uint64_t lastOld;    // the last execution that changed the field: before ...
    uint64_t lastNew;    // ... and after
    uint32_t exec;       // executions
    uint32_t chg;        // executions that changed the field
    uint32_t lastTick;   // frame counter at the last execution
    uint32_t ticks;      // ticks with at least one execution
    uint32_t run;        // current run of consecutive such ticks
    uint32_t maxRun;
    uint32_t ctx;        // bit n: executed on a tick whose mode byte was n
    uint32_t lastChg;    // frame counter at the last change
    uint32_t chgTicks;   // ticks with at least one change
    uint32_t chgRun;
    uint32_t maxChgRun;
    uint32_t ticksM1;    // ticks executed with mode byte 1 (a 60 Hz stock context)
    uint32_t pad[2];
};
static_assert(sizeof(TracerRec) == kTracerRecSize, "layout shared with tools/gen_tracer.py");
static_assert(offsetof(TracerRec, exec) == 0x18, "layout shared with tools/gen_tracer.py");
static_assert(offsetof(TracerRec, lastChg) == 0x34, "layout shared with tools/gen_tracer.py");
static_assert(offsetof(TracerRec, ticksM1) == 0x44, "layout shared with tools/gen_tracer.py");

static const int kTrWindows = (int)(sizeof(kTracerWindows) / sizeof(kTracerWindows[0]));
static const int kTrSites = (int)(sizeof(kTracerSites) / sizeof(kTracerSites[0]));
static const int kTrInsns = (int)(sizeof(kTracerInsns) / sizeof(kTracerInsns[0]));
static const int kTrSubs = (int)(sizeof(kTracerSubsystems) / sizeof(kTracerSubsystems[0]));

// The route. One step per tracer-key press.
static const char* const kTracerRoute[] = {
    "boot to the title screen, then wait 10 s on it",
    "Options: open every page, then back out",
    "load a save (the loading screen is part of it)",
    "pause menu: open every tab, then close it",
    "walk through an area exit (loading screen + transition)",
    "first areas: 20 s by the torches, 20 s by the portal",
    "a battle, using brush techniques",
    "a shop: browse the list, buy something",
    "save the game (memory-card screen)",
};
static const int kTracerSteps = (int)(sizeof(kTracerRoute) / sizeof(kTracerRoute[0]));

struct TracerCfg {
    bool enabled = true;
    UINT nextVk = VK_F4;
    char nextName[32] = "F4";
    int shedPerSecond = 300000;
    int autosaveSeconds = 60;
};
static TracerCfg g_tcfg;

static uint8_t* g_trPool = nullptr;
static TracerRec* g_trRec = nullptr;
static uint8_t g_trState[kTrWindows];     // 0 not installed, 1 installed, 2 shed
static int g_trFirstSite[kTrWindows];
static int g_trSiteCount[kTrWindows];
static uint64_t g_trPrevExec[kTrWindows];
static bool g_trInstalled = false;
static bool g_trFailed = false;
static int g_trInstalledCount = 0;
static int g_trShedCount = 0;
static int g_trPhase = 0;                 // index of the step being recorded
static uint32_t g_trPhaseFc0 = 0;
static LONGLONG g_trPhaseT0 = 0;
static uint32_t g_trModeSamples[3];       // other / mode 1 / mode 2, sampled at 100 Hz
static int g_trSlowSeconds = 0;           // seconds this step spent under 27 ticks/s
static int g_trLive = 0;                  // sites that changed their field in the last 30 ticks
static int g_trLiveUi = 0;
static uint32_t g_trLastFc = 0;
static volatile LONG g_trNetHits = 0;
static volatile LONG g_trNetLogged = 0;
static uint32_t g_trNetRva[16];
static int g_trUiSub[8];
static int g_trUiSubs = 0;

static void tracerLoadConfig(const char* ini) {
    const char* sec = "Tracer";
    g_tcfg.enabled = GetPrivateProfileIntA(sec, "Enabled", 1, ini) != 0;
    GetPrivateProfileStringA(sec, "NextKey", "F4", g_tcfg.nextName, sizeof(g_tcfg.nextName), ini);
    g_tcfg.nextVk = parseVk(g_tcfg.nextName);
    g_tcfg.shedPerSecond = GetPrivateProfileIntA(sec, "ShedPerSecond", 300000, ini);
    g_tcfg.autosaveSeconds = GetPrivateProfileIntA(sec, "AutosaveSeconds", 60, ini);
    if (g_tcfg.autosaveSeconds < 5) {
        g_tcfg.autosaveSeconds = 5;
    }
    logf("tracer config: Enabled=%d NextKey=%s (vk 0x%X) ShedPerSecond=%d AutosaveSeconds=%d",
         (int)g_tcfg.enabled, g_tcfg.nextName, g_tcfg.nextVk, g_tcfg.shedPerSecond,
         g_tcfg.autosaveSeconds);
}

// window whose bytes contain rva, or -1 (kTracerWindows is sorted by rva)
static int trWindowAt(uint32_t rva) {
    int lo = 0, hi = kTrWindows - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        const TracerWindow& w = kTracerWindows[mid];
        if (rva < w.rva) {
            hi = mid - 1;
        } else if (rva >= w.rva + w.len) {
            lo = mid + 1;
        } else {
            return mid;
        }
    }
    return -1;
}

// The int3 net. Bytes 5.. of every window are int3; a thread only reaches one
// if something branches into the middle of a window, which the generator
// believes nothing does. If it happens anyway, resume the thread at the same
// instruction inside the stub -- verify_tracer.py checks every such entry point
// -- and remember where, so the log can name the missed branch target.
static LONG CALLBACK tracerNet(EXCEPTION_POINTERS* ep) {
    if (ep->ExceptionRecord->ExceptionCode != EXCEPTION_BREAKPOINT || !g_trPool) {
        return EXCEPTION_CONTINUE_SEARCH;
    }
    uintptr_t a = (uintptr_t)ep->ExceptionRecord->ExceptionAddress;
    uintptr_t m = (uintptr_t)g_eng.main;
    if (a < m || a - m > 0xFFFFFFFFull) {
        return EXCEPTION_CONTINUE_SEARCH;
    }
    uint32_t rva = (uint32_t)(a - m);
    int lo = 0, hi = kTrInsns - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (kTracerInsns[mid].rva < rva) {
            lo = mid + 1;
        } else if (kTracerInsns[mid].rva > rva) {
            hi = mid - 1;
        } else {
            int w = trWindowAt(rva);
            if (w < 0 || g_trState[w] != 1) {
                return EXCEPTION_CONTINUE_SEARCH;
            }
            ep->ContextRecord->Rip = (DWORD64)(g_trPool + kTracerInsns[mid].stub);
            LONG n = InterlockedIncrement(&g_trNetHits);
            if (n <= 16) {
                g_trNetRva[n - 1] = rva;
            }
            return EXCEPTION_CONTINUE_EXECUTION;
        }
    }
    return EXCEPTION_CONTINUE_SEARCH;
}

// ---- thread suspension -------------------------------------------------
// suspendOthers / resumeOthers (dinput8_proxy.cpp) stop every other thread
// and record where each one stopped in g_susRip.

// true if some suspended thread is stopped strictly inside a listed window
static bool trThreadInside(const uint8_t* selected) {
    uintptr_t m = (uintptr_t)g_eng.main;
    for (int i = 0; i < g_susCount; i++) {
        DWORD64 rip = g_susRip[i];
        if (rip <= m || rip - m > 0xFFFFFFFFull) {
            continue;
        }
        uint32_t rva = (uint32_t)(rip - m);
        int w = trWindowAt(rva);
        if (w >= 0 && rva != kTracerWindows[w].rva && selected[w]) {
            return true;
        }
    }
    return false;
}

// Write the jump (install) or the original bytes (shed) of every selected
// window, with the other threads suspended. Returns false if a thread stayed
// inside a selected window through every retry.
static bool trWriteWindows(const uint8_t* selected, bool install, const uint8_t* patches) {
    uint32_t lo = 0xFFFFFFFFu, hi = 0;
    for (int w = 0; w < kTrWindows; w++) {
        if (selected[w]) {
            lo = kTracerWindows[w].rva < lo ? kTracerWindows[w].rva : lo;
            uint32_t e = kTracerWindows[w].rva + kTracerWindows[w].len;
            hi = e > hi ? e : hi;
        }
    }
    if (lo >= hi) {
        return true;
    }
    uint8_t* base = g_eng.main;
    for (int attempt = 0; attempt < 200; attempt++) {
        suspendOthers();
        if (trThreadInside(selected)) {
            resumeOthers();
            Sleep(1);
            continue;
        }
        DWORD old;
        if (!VirtualProtect(base + lo, hi - lo, PAGE_EXECUTE_READWRITE, &old)) {
            resumeOthers();
            return false;
        }
        for (int w = 0; w < kTrWindows; w++) {
            if (!selected[w]) {
                continue;
            }
            const TracerWindow& tw = kTracerWindows[w];
            if (install) {
                memcpy(base + tw.rva, patches + (size_t)w * 32, tw.len);
            } else {
                memcpy(base + tw.rva, kTracerOrig + tw.orig, tw.len);
            }
        }
        VirtualProtect(base + lo, hi - lo, old, &old);
        FlushInstructionCache(GetCurrentProcess(), base + lo, hi - lo);
        resumeOthers();
        return true;
    }
    return false;
}

static bool tracerInstall() {
    if (!g_tcfg.enabled) {
        logf("tracer: Enabled=0, not installed");
        return false;
    }
    uint8_t* main = g_eng.main;
    logf("tracer: %d sites in %d windows, generated for main.dll sha1 %s", kTrSites, kTrWindows,
         TRACER_MAIN_SHA1);
    // 1. every window must hold exactly the bytes the stubs were built from
    int bad = 0;
    for (int w = 0; w < kTrWindows; w++) {
        const TracerWindow& tw = kTracerWindows[w];
        if (w && tw.rva < kTracerWindows[w - 1].rva + kTracerWindows[w - 1].len) {
            logf("tracer: windows out of order at main+%X -- regenerate the header", tw.rva);
            g_trFailed = true;
            return false;
        }
        if (tw.len > 32 || memcmp(main + tw.rva, kTracerOrig + tw.orig, tw.len) != 0) {
            bad++;
        }
    }
    if (bad) {
        logf("tracer: %d of %d windows do not hold the expected bytes -- this main.dll is not the"
             " build the header was generated from; nothing installed", bad, kTrWindows);
        g_trFailed = true;
        return false;
    }
    // 2. the pool: code, fixups, records
    uint8_t* pool = allocNear(main, kTracerPoolSize);
    if (!pool) {
        logf("tracer: no %u KB region within reach of main.dll", kTracerPoolSize / 1024);
        g_trFailed = true;
        return false;
    }
    memcpy(pool + kTracerCodeOffset, kTracerCode, sizeof(kTracerCode));
    for (const TracerFixup& f : kTracerFixups) {
        uint8_t* target = main + f.target;
        if (f.next == 0) {
            uint64_t abs = (uint64_t)target;
            memcpy(pool + f.field, &abs, 8);
            continue;
        }
        int64_t rel = (int64_t)target - (int64_t)(pool + f.next);
        if (rel != (int32_t)rel) {
            logf("tracer: pool out of rel32 reach of main+%X", f.target);
            g_trFailed = true;
            return false;
        }
        int32_t r32 = (int32_t)rel;
        memcpy(pool + f.field, &r32, 4);
    }
    g_trRec = (TracerRec*)pool;
    for (int i = 0; i < kTrSites; i++) {
        g_trRec[i].lastTick = 0xFFFFFFFEu;
        g_trRec[i].lastChg = 0xFFFFFFFEu;
        int w = (int)kTracerSites[i].window;
        if (g_trSiteCount[w]++ == 0) {
            g_trFirstSite[w] = i;
        }
    }
    for (int s = 0; s < kTrSubs; s++) {
        if (!strncmp(kTracerSubsystems[s], "ui", 2) && g_trUiSubs < 8) {
            g_trUiSub[g_trUiSubs++] = s;
        }
    }
    FlushInstructionCache(GetCurrentProcess(), pool, kTracerPoolSize);
    // 3. the patch bytes: jmp stub, then int3 to the end of the window
    uint8_t* patches = (uint8_t*)calloc((size_t)kTrWindows, 32);
    uint8_t* selected = (uint8_t*)calloc((size_t)kTrWindows, 1);
    if (!patches || !selected) {
        logf("tracer: out of memory");
        free(patches);
        free(selected);
        g_trFailed = true;
        return false;
    }
    for (int w = 0; w < kTrWindows; w++) {
        const TracerWindow& tw = kTracerWindows[w];
        uint8_t* p = patches + (size_t)w * 32;
        int64_t rel = (int64_t)(pool + tw.stub) - (int64_t)(main + tw.rva + 5);
        if (rel != (int32_t)rel) {
            continue;
        }
        int32_t r32 = (int32_t)rel;
        p[0] = 0xE9;
        memcpy(p + 1, &r32, 4);
        memset(p + 5, 0xCC, tw.len - 5);
        selected[w] = 1;
    }
    g_trPool = pool;
    AddVectoredExceptionHandler(1, tracerNet);
    // 4. write them all with the game's threads stopped
    LONGLONG t0 = qpc();
    bool ok = trWriteWindows(selected, true, patches);
    double ms = (double)(qpc() - t0) * 1000.0 / (double)g_qpcFreq;
    if (!ok) {
        logf("tracer: a game thread stayed inside a window for 200 attempts; nothing installed");
        free(patches);
        free(selected);
        g_trFailed = true;
        return false;
    }
    for (int w = 0; w < kTrWindows; w++) {
        g_trState[w] = selected[w];
        g_trInstalledCount += selected[w];
    }
    free(patches);
    free(selected);
    g_trInstalled = true;
    g_trPhaseFc0 = g_eng.frameCounter ? *g_eng.frameCounter : 0;
    g_trPhaseT0 = qpc();
    logf("tracer: installed %d of %d windows at pool %p in %.1f ms", g_trInstalledCount,
         kTrWindows, (void*)pool, ms);
    logf("tracer: route step 1/%d: %s -- press %s when done", kTracerSteps, kTracerRoute[0],
         g_tcfg.nextName);
    return true;
}

static void trSlug(const char* s, char* out, size_t n) {
    size_t k = 0;
    bool under = false;
    for (; *s && k + 1 < n && k < 40; s++) {
        char c = *s;
        if (isalnum((unsigned char)c)) {
            out[k++] = (char)tolower((unsigned char)c);
            under = false;
        } else if (!under && k) {
            out[k++] = '_';
            under = true;
        }
        if (c == '(' || c == ',' || c == ':') {
            break;
        }
    }
    while (k && out[k - 1] == '_') {
        k--;
    }
    out[k] = 0;
}

static const char* trStepLabel(int phase, char* buf, size_t n) {
    if (phase < kTracerSteps) {
        return kTracerRoute[phase];
    }
    snprintf(buf, n, "extra phase %d", phase - kTracerSteps + 1);
    return buf;
}

// Which run of the game wrote a file: the process's start, UTC to the
// millisecond, and its id. tools/tracer_report.py tells runs apart by this and
// orders them by the start, so an old run's snapshot never passes for this
// one's. The frame counter cannot do it: it restarts with every launch, from
// the same value.
static const char* trSession() {
    static char s[64];
    if (!s[0]) {
        FILETIME created, exited, kernel, user;
        SYSTEMTIME st;
        if (GetProcessTimes(GetCurrentProcess(), &created, &exited, &kernel, &user) &&
            FileTimeToSystemTime(&created, &st)) {
            snprintf(s, sizeof(s), "%04u-%02u-%02uT%02u:%02u:%02u.%03uZ pid %lu",
                     (unsigned)st.wYear, (unsigned)st.wMonth, (unsigned)st.wDay,
                     (unsigned)st.wHour, (unsigned)st.wMinute, (unsigned)st.wSecond,
                     (unsigned)st.wMilliseconds, (unsigned long)GetCurrentProcessId());
        } else {
            snprintf(s, sizeof(s), "unknown pid %lu", (unsigned long)GetCurrentProcessId());
        }
    }
    return s;
}

// Write the records to okami_tracer\phaseNN_<step>[suffix].csv. `reset`
// clears the counts for the next phase (a site mid-update on a game thread can
// lose one count; that is noise, not a pattern).
static void tracerDump(const char* suffix, bool reset, bool atExit) {
    if (!g_trRec) {
        return;
    }
    char dir[MAX_PATH];
    snprintf(dir, sizeof(dir), "%sokami_tracer", g_baseDir);
    CreateDirectoryA(dir, nullptr);
    char lbuf[48];
    const char* label = trStepLabel(g_trPhase, lbuf, sizeof(lbuf));
    char slug[48];
    trSlug(label, slug, sizeof(slug));
    char path[MAX_PATH];
    snprintf(path, sizeof(path), "%s\\phase%02d_%s%s.csv", dir, g_trPhase + 1, slug, suffix);
    FILE* f = fopen(path, "w");
    if (!f) {
        logf("tracer: cannot write %s", path);
        return;
    }
    uint32_t fc = atExit ? g_trLastFc : (g_eng.frameCounter ? *g_eng.frameCounter : 0);
    double secs = (double)(qpc() - g_trPhaseT0) / (double)g_qpcFreq;
    fprintf(f, "# okami tracer phase %d: %s\n", g_trPhase + 1, label);
    fprintf(f, "# ticks %u (frame counter %u..%u), %.1f s = %.2f ticks/s, slow %d s,"
               " mode samples other/1/2 %u/%u/%u\n",
            fc - g_trPhaseFc0, g_trPhaseFc0, fc, secs,
            secs > 0.0 ? (double)(fc - g_trPhaseFc0) / secs : 0.0, g_trSlowSeconds,
            g_trModeSamples[0], g_trModeSamples[1], g_trModeSamples[2]);
    fprintf(f, "# sites %d, windows installed %d, shed %d, int3-net hits %ld, main.dll sha1 %s\n",
            kTrSites, g_trInstalledCount, g_trShedCount, (long)g_trNetHits, TRACER_MAIN_SHA1);
    fprintf(f, "# session %s\n", trSession());
    fprintf(f, "site,subsystem,sample,kind,exec,changed,ticks,max_run,chg_ticks,max_chg_run,"
               "ctx,ticks_m1,last_old,last_new,window_state\n");
    int written = 0, clocks = 0, uiClocks = 0;
    for (int i = 0; i < kTrSites; i++) {
        TracerRec r = g_trRec[i];
        if (!r.exec) {
            continue;
        }
        const TracerSite& s = kTracerSites[i];
        fprintf(f, "%06X,%s,%u,%u,%u,%u,%u,%u,%u,%u,%X,%u,%llX,%llX,%u\n", s.rva,
                kTracerSubsystems[s.sub], s.sample, s.kind, r.exec, r.chg, r.ticks, r.maxRun,
                r.chgTicks, r.maxChgRun, r.ctx, r.ticksM1, (unsigned long long)r.lastOld,
                (unsigned long long)r.lastNew, g_trState[s.window]);
        written++;
        if (r.maxChgRun >= 8) {
            clocks++;
            for (int u = 0; u < g_trUiSubs; u++) {
                if (s.sub == g_trUiSub[u]) {
                    uiClocks++;
                }
            }
        }
    }
    fclose(f);
    if (!atExit) {
        logf("tracer: wrote %s -- %d sites ran, %d changed on 8+ consecutive ticks (%d UI)", path,
             written, clocks, uiClocks);
    }
    if (reset) {
        for (int i = 0; i < kTrSites; i++) {
            TracerRec& r = g_trRec[i];
            r.exec = r.chg = r.ticks = r.run = r.maxRun = r.ctx = 0;
            r.chgTicks = r.chgRun = r.maxChgRun = r.ticksM1 = 0;
            r.lastOld = r.lastNew = 0;
            r.lastTick = r.lastChg = 0xFFFFFFFEu;
        }
        memset(g_trPrevExec, 0, sizeof(g_trPrevExec));
        memset(g_trModeSamples, 0, sizeof(g_trModeSamples));
        g_trSlowSeconds = 0;
        g_trPhaseFc0 = fc;
        g_trPhaseT0 = qpc();
    }
}

// Put back the original bytes of every window whose sites ran more than
// ShedPerSecond times a second over the last `secs` -- and, when `busiest` is
// set because the game has been ticking slowly, also of the eight busiest
// windows above 20000 a second.
static void trShed(double secs, bool busiest) {
    static uint8_t sel[kTrWindows];
    static double rate[kTrWindows];
    int n = 0;
    for (int w = 0; w < kTrWindows; w++) {
        sel[w] = 0;
        rate[w] = 0.0;
        if (g_trState[w] != 1) {
            continue;
        }
        uint64_t sum = 0;
        for (int k = 0; k < g_trSiteCount[w]; k++) {
            sum += g_trRec[g_trFirstSite[w] + k].exec;
        }
        uint64_t delta = sum >= g_trPrevExec[w] ? sum - g_trPrevExec[w] : sum;
        g_trPrevExec[w] = sum;
        rate[w] = (double)delta / secs;
        if (g_tcfg.shedPerSecond > 0 && rate[w] > (double)g_tcfg.shedPerSecond) {
            sel[w] = 1;
            n++;
            logf("tracer: shedding window main+%X (%.0f executions/s)", kTracerWindows[w].rva,
                 rate[w]);
        }
    }
    for (int pick = 0; busiest && pick < 8; pick++) {
        int best = -1;
        for (int w = 0; w < kTrWindows; w++) {
            if (!sel[w] && rate[w] > 20000.0 && (best < 0 || rate[w] > rate[best])) {
                best = w;
            }
        }
        if (best < 0) {
            break;
        }
        sel[best] = 1;
        n++;
        logf("tracer: game ticking slowly -- shedding window main+%X (%.0f executions/s)",
             kTracerWindows[best].rva, rate[best]);
    }
    if (!n) {
        return;
    }
    if (trWriteWindows(sel, false, nullptr)) {
        for (int w = 0; w < kTrWindows; w++) {
            if (sel[w]) {
                g_trState[w] = 2;
                g_trShedCount++;
            }
        }
    } else {
        logf("tracer: shedding failed (a thread stayed inside the window)");
    }
}

// Called from the watcher loop (~100 Hz).
static void tracerPoll() {
    if (!g_trInstalled) {
        return;
    }
    uint32_t fc = g_eng.frameCounter ? *g_eng.frameCounter : 0;
    g_trLastFc = fc;
    uint8_t mode = g_eng.modeByte ? *(volatile uint8_t*)g_eng.modeByte : 0;
    g_trModeSamples[mode == 1 ? 1 : (mode == 2 ? 2 : 0)]++;

    static bool keyWasDown = false;
    if (g_tcfg.nextVk) {
        bool down = (GetAsyncKeyState((int)g_tcfg.nextVk) & 0x8000) != 0;
        if (down && !keyWasDown && (!g_cfg.requireFocus || gameHasFocus())) {
            char lbuf[48];
            logf("==== TRACER step %d done: %s ====", g_trPhase + 1,
                 trStepLabel(g_trPhase, lbuf, sizeof(lbuf)));
            tracerDump("", true, false);
            // the partial file of the finished step is superseded
            char dir[MAX_PATH], slug[48], path[MAX_PATH];
            snprintf(dir, sizeof(dir), "%sokami_tracer", g_baseDir);
            trSlug(trStepLabel(g_trPhase, lbuf, sizeof(lbuf)), slug, sizeof(slug));
            snprintf(path, sizeof(path), "%s\\phase%02d_%s.partial.csv", dir, g_trPhase + 1, slug);
            DeleteFileA(path);
            g_trPhase++;
            logf("tracer: route step %d/%d: %s", g_trPhase + 1, kTracerSteps,
                 trStepLabel(g_trPhase, lbuf, sizeof(lbuf)));
            if (g_cfg.beep) {
                MessageBeep(MB_OK);
            }
        }
        keyWasDown = down;
    }

    static LONGLONG lastLive = 0, lastSave = 0, lastShed = 0;
    LONGLONG now = qpc();
    if (lastSave == 0) {
        lastLive = lastSave = lastShed = now;
    }
    if (now - lastLive >= g_qpcFreq) {
        lastLive = now;
        int live = 0, liveUi = 0;
        for (int i = 0; i < kTrSites; i++) {
            if (g_trRec[i].chgTicks && fc - g_trRec[i].lastChg <= 30) {
                live++;
                for (int u = 0; u < g_trUiSubs; u++) {
                    if (kTracerSites[i].sub == g_trUiSub[u]) {
                        liveUi++;
                    }
                }
            }
        }
        g_trLive = live;
        g_trLiveUi = liveUi;
        LONG hits = g_trNetHits;
        while (g_trNetLogged < hits && g_trNetLogged < 16) {
            logf("tracer: int3 net caught a branch into main+%X (redirected into its stub)",
                 g_trNetRva[g_trNetLogged]);
            g_trNetLogged++;
        }
    }
    static uint32_t shedFc = 0;
    static int slowStreak = 0;
    if (now - lastShed >= 2 * g_qpcFreq) {
        double secs = (double)(now - lastShed) / (double)g_qpcFreq;
        lastShed = now;
        // stock ticks at 30 (60 in some menus) and never slower, so under 27
        // for three checks in a row means the stubs are costing too much
        double tps = shedFc ? (double)(fc - shedFc) / secs : 30.0;
        shedFc = fc;
        bool slow = tps > 1.0 && tps < 27.0;
        if (slow) {
            g_trSlowSeconds += (int)(secs + 0.5);
        }
        slowStreak = slow ? slowStreak + 1 : 0;
        bool busiest = slowStreak >= 3;
        if (busiest) {
            logf("tracer: %.1f ticks/s for 6 s -- shedding the busiest windows", tps);
            slowStreak = 0;
        }
        trShed(secs, busiest);
    }
    if (now - lastSave >= (LONGLONG)g_tcfg.autosaveSeconds * g_qpcFreq) {
        lastSave = now;
        tracerDump(".partial", false, false);
    }
}

// The overlay's two lines while the tracer build runs. False = not the tracer's turn.
static bool tracerOverlay(char* line, size_t n, double tickHz) {
    if (!g_trInstalled) {
        if (g_trFailed) {
            snprintf(line, n, "TRACER NOT INSTALLED -- see okami_hackfix.log\n"
                              "stock game, nothing is being recorded");
            return true;
        }
        return false;
    }
    char lbuf[48];
    const char* label = trStepLabel(g_trPhase, lbuf, sizeof(lbuf));
    if (g_trPhase < kTracerSteps) {
        snprintf(line, n, "TRACER step %d/%d -- %s when done | %d live (%d UI) | %.0f Hz%s\n%s",
                 g_trPhase + 1, kTracerSteps, g_tcfg.nextName, g_trLive, g_trLiveUi, tickHz,
                 g_trShedCount ? " | shed" : "", label);
    } else {
        snprintf(line, n, "TRACER route done -- you can quit | %d live (%d UI) | %.0f Hz\n"
                          "recording %s (%s saves it)",
                 g_trLive, g_trLiveUi, tickHz, label, g_tcfg.nextName);
    }
    return true;
}

static void tracerAtExit() {
    if (g_trInstalled) {
        tracerDump(".exit", false, true);
    }
}

// Offline self-test, driven by tools/tracer_selftest.py without the game:
// maps main.dll into the calling process (DONT_RESOLVE_DLL_REFERENCES: no
// DllMain, no imports, nothing of the game runs), installs exactly as in the
// game, and writes what it produced so the script can compare it with the
// emulator-verified pool. Then exercises the int3 net's lookup, shedding and
// the dump. Returns 0 on success; failures are also written to report.txt.
extern "C" __declspec(dllexport) int OkamiTracerSelfTest(const char* mainPath, const char* outDir) {
    char path[MAX_PATH];
    snprintf(path, sizeof(path), "%s\\report.txt", outDir);
    FILE* rep = fopen(path, "w");
    if (!rep) {
        return 2;
    }
    int fails = 0;
    HMODULE m = LoadLibraryExA(mainPath, nullptr, DONT_RESOLVE_DLL_REFERENCES);
    if (!m) {
        fprintf(rep, "FAIL load %s (%lu)\n", mainPath, GetLastError());
        fclose(rep);
        return 1;
    }
    g_eng.main = (uint8_t*)m;
    if (!tracerInstall()) {
        fprintf(rep, "FAIL install (see okami_hackfix.log)\n");
        fclose(rep);
        return 1;
    }
    fprintf(rep, "main %p\npool %p\ninstalled %d of %d\n", (void*)m, (void*)g_trPool,
            g_trInstalledCount, kTrWindows);
    // what the install produced: the pool and every window as it now reads
    snprintf(path, sizeof(path), "%s\\pool.bin", outDir);
    if (FILE* f = fopen(path, "wb")) {
        fwrite(g_trPool, 1, kTracerPoolSize, f);
        fclose(f);
    }
    snprintf(path, sizeof(path), "%s\\windows.bin", outDir);
    if (FILE* f = fopen(path, "wb")) {
        for (int w = 0; w < kTrWindows; w++) {
            fwrite(g_eng.main + kTracerWindows[w].rva, 1, kTracerWindows[w].len, f);
        }
        fclose(f);
    }
    // the int3 net: every interior instruction resolves to its stub offset,
    // and addresses that are not interior starts are left alone
    int netOk = 0;
    for (int i = 0; i < kTrInsns; i++) {
        EXCEPTION_RECORD er;
        CONTEXT ctx;
        memset(&er, 0, sizeof(er));
        memset(&ctx, 0, sizeof(ctx));
        er.ExceptionCode = EXCEPTION_BREAKPOINT;
        er.ExceptionAddress = g_eng.main + kTracerInsns[i].rva;
        EXCEPTION_POINTERS ep = {&er, &ctx};
        LONG r = tracerNet(&ep);
        if (r != EXCEPTION_CONTINUE_EXECUTION ||
            ctx.Rip != (DWORD64)(g_trPool + kTracerInsns[i].stub)) {
            if (fails++ < 10) {
                fprintf(rep, "FAIL net main+%X -> %llX\n", kTracerInsns[i].rva,
                        (unsigned long long)ctx.Rip);
            }
        } else {
            netOk++;
        }
    }
    {
        EXCEPTION_RECORD er;
        CONTEXT ctx;
        memset(&er, 0, sizeof(er));
        memset(&ctx, 0, sizeof(ctx));
        er.ExceptionCode = EXCEPTION_BREAKPOINT;
        er.ExceptionAddress = g_eng.main + kTracerWindows[0].rva;  // a window start, not interior
        EXCEPTION_POINTERS ep = {&er, &ctx};
        if (tracerNet(&ep) != EXCEPTION_CONTINUE_SEARCH) {
            fails++;
            fprintf(rep, "FAIL net claimed a window start\n");
        }
    }
    fprintf(rep, "net %d of %d\n", netOk, kTrInsns);
    InterlockedExchange(&g_trNetHits, 0);
    // shedding puts the original bytes back and marks the window
    int w0 = (int)kTracerSites[0].window;
    g_trPrevExec[w0] = 0;
    g_trRec[0].exec = 0x7FFFFFFF;
    trShed(1.0, false);
    if (g_trState[w0] != 2 ||
        memcmp(g_eng.main + kTracerWindows[w0].rva, kTracerOrig + kTracerWindows[w0].orig,
               kTracerWindows[w0].len) != 0) {
        fails++;
        fprintf(rep, "FAIL shed window main+%X\n", kTracerWindows[w0].rva);
    } else {
        fprintf(rep, "shed ok main+%X\n", kTracerWindows[w0].rva);
    }
    g_trRec[0].exec = 0;
    // a record with known contents appears in the dump, and reset clears it
    g_trRec[1].exec = 7;
    g_trRec[1].maxChgRun = 9;
    tracerDump(".selftest", true, false);
    if (g_trRec[1].exec != 0 || g_trRec[1].lastTick != 0xFFFFFFFEu) {
        fails++;
        fprintf(rep, "FAIL reset\n");
    }
    fprintf(rep, "%s\n", fails ? "FAILED" : "PASS");
    fclose(rep);
    return fails ? 1 : 0;
}
